pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/Mins00oo/umzip.git'
        BACKEND_DIR = 'backend'
        DOCKER_IMAGE = 'be-app' // Docker 이미지 이름
        CONTAINER_NAME = 'backend-application' // Docker 컨테이너 이름
    }

    parameters {
        string(name: 'DB_URL', defaultValue: '', description: 'Database URL')
        string(name: 'DB_USERNAME', defaultValue: '', description: 'Database Username')
        string(name: 'DB_PASSWORD', defaultValue: '', description: 'Database Password')
        string(name: 'JWT_SECRET_KEY', defaultValue: '', description: 'JWT Secret Key')
        string(name: 'JWT_ACCESS_EXPIRED_TIME_MS', defaultValue: '', description: 'JWT Access Token Expiration Time')
        string(name: 'S3_ACCESS_KEY', defaultValue: '', description: 'AWS S3 Access Key')
        string(name: 'S3_SECRET_KEY', defaultValue: '', description: 'AWS S3 Secret Key')
        string(name: 'S3_BUCKET', defaultValue: '', description: 'AWS S3 Bucket Name')
        string(name: 'S3_REGION', defaultValue: '', description: 'AWS S3 Region')
        string(name: 'REDIS_HOST', defaultValue: '', description: 'Redis Host')
        string(name: 'REDIS_PASSWORD', defaultValue: '', description: 'Redis Password')
        string(name: 'COOL_SMS_API_KEY', defaultValue: '', description: 'Cool SMS API Key')
        string(name: 'COOL_SMS_API_SECRET', defaultValue: '', description: 'Cool SMS API Secret')
        string(name: 'JWT_REFRESH_EXPIRED_TIME_MS', defaultValue: '', description: 'JWT Refresh Token Expiration Time')
        string(name: 'BUSINESS_SERVICE_KEY', defaultValue: '', description: 'Business Service Key')
        string(name: 'KAKAO_API_KEY', defaultValue: '', description: 'Kakao API Key')
        string(name: 'FUEL_API_KEY', defaultValue: '', description: 'Fuel API Key')
        string(name: 'MONGO_URI', defaultValue: '', description: 'MongoDB URI')
        // 필요한 만큼 추가
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: 'main']],
                          userRemoteConfigs: [[url: "${REPO_URL}", credentialsId: 'accesstoken_username']]
                ])
                dir("${BACKEND_DIR}") {
                    echo "Moved to ${BACKEND_DIR} directory"
                }
            }
        }

        stage('Tests') {
            steps {
                dir("${BACKEND_DIR}") {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew test'
                }
            }
        }

        stage('Build') {
            steps {
                dir("${BACKEND_DIR}") {
                    // application.yml 파일이 위치한 디렉토리로 이동
                    dir('src/main/resources') {
                        // 변수 치환
                        sh """
                        sed -i 's#\\\${DB_URL}#${params.DB_URL}#g' application.yml
                        sed -i 's#\\\${DB_USERNAME}#${params.DB_USERNAME}#g' application.yml
                        sed -i 's#\\\${DB_PASSWORD}#${params.DB_PASSWORD}#g' application.yml
                        sed -i 's#\\\${JWT_SECRET_KEY}#${params.JWT_SECRET_KEY}#g' application.yml
                        sed -i 's#\\\${JWT_ACCESS_EXPIRED_TIME_MS}#${params.JWT_ACCESS_EXPIRED_TIME_MS}#g' application.yml
                        sed -i 's#\\\${JWT_REFRESH_EXPIRED_TIME_MS}#${params.JWT_REFRESH_EXPIRED_TIME_MS}#g' application.yml
                        sed -i 's#\\\${S3_ACCESS_KEY}#${params.S3_ACCESS_KEY}#g' application.yml
                        sed -i 's#\\\${S3_SECRET_KEY}#${params.S3_SECRET_KEY}#g' application.yml
                        sed -i 's#\\\${S3_BUCKET}#${params.S3_BUCKET}#g' application.yml
                        sed -i 's#\\\${S3_REGION}#${params.S3_REGION}#g' application.yml
                        sed -i 's#\\\${REDIS_HOST}#${params.REDIS_HOST}#g' application.yml
                        sed -i 's#\\\${REDIS_PASSWORD}#${params.REDIS_PASSWORD}#g' application.yml
                        sed -i 's#\\\${COOL_SMS_API_KEY}#${params.COOL_SMS_API_KEY}#g' application.yml
                        sed -i 's#\\\${COOL_SMS_API_SECRET}#${params.COOL_SMS_API_SECRET}#g' application.yml
                        sed -i 's#\\\${BUSINESS_SERVICE_KEY}#${params.BUSINESS_SERVICE_KEY}#g' application.yml
                        sed -i 's#\\\${KAKAO_API_KEY}#${params.KAKAO_API_KEY}#g' application.yml
                        sed -i 's#\\\${FUEL_API_KEY}#${params.FUEL_API_KEY}#g' application.yml
                        sed -i 's#\\\${MONGO_URI}#${params.MONGO_URI}#g' application.yml
                        """
                    }
                    // 프로젝트 루트 디렉토리로 이동하여 빌드 수행
                    sh './gradlew clean build'
                }
            }
        }


        stage('Stop and Remove Existing Docker Container') {
            steps {
                // 기존 도커 컨테이너 중지 및 삭제
                script {
                    // 이미 실행 중인 컨테이너를 중지
                    sh """
                    if [ \$(docker ps -q -f name=${CONTAINER_NAME}) ]; then
                        echo "Stopping running container: ${CONTAINER_NAME}"
                        docker stop ${CONTAINER_NAME}
                    fi
                    """
                    // 컨테이너 삭제
                    sh """
                    if [ \$(docker ps -a -q -f name=${CONTAINER_NAME}) ]; then
                        echo "Removing container: ${CONTAINER_NAME}"
                        docker rm ${CONTAINER_NAME}
                    fi
                    """
                    // 기존 도커 이미지를 삭제
                    sh """
                    if [ \$(docker images -q ${DOCKER_IMAGE}) ]; then
                        echo "Removing image: ${DOCKER_IMAGE}"
                        docker rmi -f ${DOCKER_IMAGE}
                    fi
                    """
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                dir("${BACKEND_DIR}") {
                    sh """
                    echo "Building new Docker image: ${DOCKER_IMAGE}"
                    docker build -t ${DOCKER_IMAGE} .

                    echo "Running new Docker container: ${CONTAINER_NAME}"
                    docker run -d --name ${CONTAINER_NAME} -p 8080:8080 ${DOCKER_IMAGE}
                    """
                }
            }
        }
    }

    post {
        always {
            // 빌드 완료 후 결과 출력
            echo 'Pipeline has finished'
        }
        failure {
            // 빌드 실패 시 알림 (필요시 Slack 알림 등을 추가할 수 있음)
            echo 'Build failed'
        }
    }
}
